service: alexa-skill-cuecloud

package:
  exclude:
    - bin/ffmpeg_mac

provider:
  name: aws
  runtime: nodejs4.3
  stage: prod
  region: eu-west-1
  memorySize: 512
  cfLogs: true

resources:
  Resources:
    Mp3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: spotify-preview-mp3s-for-alexa
        AccessControl: PublicReadWrite
    Mp3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: Mp3Bucket
        PolicyDocument:
          Statement:
            - Action:
                - 's3:GetObject'
              Effect: Allow
              Principal: '*'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: Mp3Bucket
                    - '/*'

functions:
  # Alexa
  alexaSkill:
    handler: skill.handler
    description: Alexa skill to listen to concerts nearby
    events:
      - alexaSkill
  # Auth
  showLoginPage:
    handler: auth.showLoginPage
    events:
      - http: GET login
  authorizeToken:
    handler: auth.authorizeToken
    events:
      - http: GET authorize/token
  authorizeByCode:
    handler: auth.authorizeByCode
    events:
      - http: GET authorize/commit-code
  # Email
  sendEmail:
    handler: email.send
    events:
      - http: POST emails
  # Events
  getEvents:
    handler: events.getEvents
    events:
      - http: GET events
  # Convert
#  getMp3:
#    handler: mp3Converter.convert
#    events:
#      - http:
#          path: convert
#          method: get
#          integration: lambda
#          request:
#            parameters:
#              querystrings:
#                mp3Url: true
#          response:
#            template: $input.path('$')
#            statusCodes:
#              301:
#                pattern: ''
#                headers:
#                  Location: integration.response.body.headers.Location
